### ISSUE TITLE
question about main.py

### ISSUE THREAD

**Issue by junyizeng** [huanranchen/AdversarialAttacks#3]
Thank you for sharing the codes in your published paper. it has been very helpful. However, while I was running the codes in my document ‘main.py’, certain problems have came out. Could you please kindly offer me some solutions to the following problems? Thank you so much. I’m looking forward to your reply.

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&confirm=t&id=1TmT5oGa1UvVjM3d-XeSj_XmKqBNRUg8r (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\pythonProject\AdversarialAttacks-main\main.py", line 22, in <module>
    Identity(Salman2020Do_R50()),
  File "E:\pythonProject\AdversarialAttacks-main\models\RobustBench\imagenet.py", line 14, in Salman2020Do_R50
    return load_model(model_name="Salman2020Do_R50", dataset="imagenet", threat_model="Linf")
  File "E:\pythonProject\AdversarialAttacks-main\robustbench\utils.py", line 148, in load_model
    download_gdrive(models[model_name]['gdrive_id'], model_path)
  File "E:\pythonProject\AdversarialAttacks-main\robustbench\utils.py", line 58, in download_gdrive
    response = session.get(url_base, params={'id': gdrive_id}, stream=True)
  File "C:\Anaconda3\envs\CWA\lib\site-packages\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "C:\Anaconda3\envs\CWA\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Anaconda3\envs\CWA\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Anaconda3\envs\CWA\lib\site-packages\requests\adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&confirm=t&id=1TmT5oGa1UvVjM3d-XeSj_XmKqBNRUg8r (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

**Comment by huanranchen** [comment]
Hi! 
Sorry for the late response. 
In main.py, some models come from RobustBench. These models need to download their checkpoints from Google drive. Most of Chinese could not visit google.com, thus causing such errors. You can either use VPN, or download these checkpoints manually following the issues in RobustBench:
https://github.com/RobustBench/robustbench/issues/54
